### ISSUE TITLE
Reduce memory usage during running multiple problems

### ISSUE THREAD

**Issue by Rekkonnect** [Rekkonnect/AdventOfCSharp#31]
Running multiple problems instantiates their static members, including memory-intensive ones like compiled regex patterns. A full validation of all problems will run through all available problems, which may result in exploded memory usage of over 500 MB from such compiled regex patterns alone.

Consider a mechanism to control loading those classes' static members, and unload a majority if usage begins to increase uncontrollably.

**Comment by AlFasGD** [comment]
This behavior might not even be that concerning in the first place, as the memory usage could scale to the user's device. Until reported as an issue by users, this won't be getting looked at.
